#!/bin/bash

echo "🔐 GitHub 账户认证"
echo "================================"
echo ""
echo "当前问题：你登录为 KAImomo99，但仓库属于 2992638402-art"
echo ""
echo "解决方案 1: 重新认证为 2992638402-art"
echo "----------------------------------------"
echo "gh auth logout"
echo "gh auth login -s workflow"
echo "# 然后选择 2992638402-art 账户"
echo ""
echo "解决方案 2: 切换账户"
echo "----------------------------------------"
echo "gh auth switch"
echo ""
echo "完成后运行："
echo "git push origin main"
echo ""
echo "================================"
echo ""
echo "📌 或者使用网页界面手动上传（推荐）："
echo "   查看 MANUAL_UPLOAD_GUIDE.md"
echo ""

